### ISSUE TITLE
adressing two muses chips parallel

### ISSUE THREAD

**Issue by frankwilker** [qhris/Muses72320#1]
Hi,
meine Programmierkenntnisse in C++ sind leider begrenzt. 
Mir ist nicht ganz klar, wie ich zwei Muses chips mit verschiedenen Adressen ansprechen kann. 
Reicht es aus, die statische Variable in eine andere Variabel zu ändern und dann die Adresse im Programmcode bei Bedarf zu ändern?
Danke für die Antworten

**Comment by frankwilker** [comment]
Sorry, fault ;)
my programming skills in C++ are unfortunately limited.
I am not quite sure how to address two Muses chips with different addresses.
Is it sufficient to change the static variable to another variable and then change the address in the program code if necessary?
Thanks for the answers

**Comment by ghost** [comment]
Have you solved your problem?
You need to create a second instance with another address.

Hast du dein Problem schon gelöst?
Du musst eine zweite Instanz erzeugen mit der Adresse des zweiten Chips auf dem SPI Bus.

Ich kenne die Adressen nicht und habe den Code nur überflogen, aber nehmen wir an sie wären 0 und 1 dann müsste es ca so aussehen:
```
byte MUSES_ADDRESS0 = 0;
Muses72320 muses0 = Muses(MUSES_ADDRESS0);

const byte MUSES_ADDRESS1 = 1;
Muses72320 muses1 = Muses(MUSES_ADDRESS1);
```

**Comment by frankwilker** [comment]
Hallo Chris,

 

Danke für die Antwort. So ungefähr kann ich mir denken, wie ich damit umgehen soll. 

Meine aktuellen Programmierfähigkeiten umfassen leider nur die C-Variante, die in der Arduino Umgebung benutzt werden. 

 

Mit C++ habe ich nicht so viel am Kopf, habe mich aber jetzt mal ein wenig, ich nenne es mal: weiter gebildet.

 

Ich werde im laufe der nächsten Woche meine Software mal umschreiben. Wäre nett, wenn ich mich da noch mal melden dürfte. Wobei ich eigentlich schon glaube, dass ich das hin bekomme.

 

Ich habe aber ein anderes Problem. Ich habe Deine Library für einen ESP32 compilieren wollen. Da gibt es eine Fehlermeldung. Du hast wahrscheinlich keine Lust, die library dafür umzuschreiben? 

Wäre auch ein komplettes Poti mit Display oder ein Vorstufenmodul für Dich drin.

 

Irgendwie komme ich mir jetzt ein bischen frech vor, direkt so offensiv vorzugehen. Aber meine Programmierfähigkeiten sind nicht mehr so dolle und ich habe ziemlich viel mit der Hardware am Kopf, so dass ich kaum dazu komme mich in dieser HInsicht weiter zu bilden.

 

Gruß Frank

 
 

Gesendet: Freitag, 13. November 2020 um 22:47 Uhr
Von: "bernerha" <notifications@github.com>
An: "qhris/Muses72320" <Muses72320@noreply.github.com>
Cc: "frankwilker" <frankwilker@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [qhris/Muses72320] adressing two muses chips parallel (#1)


 

Have you solved your problem?
You need to create a second instance with another address.

Hast du dein Problem schon gelöst?
Du musst eine zweite Instanz erzeugen mit der Adresse des zweiten Chips auf dem SPI Bus.

Ich kenne die Adressen nicht und habe den Code nur überflogen, aber nehmen wir an sie wären 0 und 1 dann müsste es ca so aussehen:

byte MUSES_ADDRESS0 = 0;

Muses72320 muses0 = Muses(MUSES_ADDRESS0);



const byte MUSES_ADDRESS1 = 1;

Muses72320 muses1 = Muses(MUSES_ADDRESS1);

**Comment by ghost** [comment]
Hi Fank,

something I have to clarify: This is not my library :)

eins gilt es zu klären: Das ist nicht meine Lib :)


Regards

**Comment by qhris** [comment]
I don't speak german. From my understanding, what @bernerha said resolves this issue, thanks for chiming in.

I tried google translate and all I can say is I have no current plans on porting this library outside arduino.
