### ISSUE TITLE
MUSES72323

### ISSUE THREAD

**Issue by gavron04** [qhris/Muses72320#2]
Hello. Maybe its possibile to make new version for muses72323? IT has new function like soft-step. https://www.njr.com/MUSES/series/MUSES72323.html

Have a good day

**Comment by qhris** [comment]
Hey. Sorry for the delayed response.
I haven't worked on this for some while, but I did do some work on the wip-1.0 branch that I believe is using the soft step function. You can check it out here: https://github.com/qhris/Muses72320/tree/wip-1.0
I don't remember what state I left it in, but you could try that out.

**Comment by qhris** [comment]
Seems I misread your comment, sorry. No, at the moment I don't have time to add in that functionality.
