### ISSUE TITLE
Circuit for Muses72320

### ISSUE THREAD

**Issue by Skylar-8** [qhris/Muses72320#3]
Hi Qhris

Do you have a typical working circuit for the Muses72320 chip, other than that shown in the datasheet? I see various parties came up with their own circuits which differ in some ways. 

In particular, I'd be interested if the 5V connected to pin 17 (D_VDD) is a requirement or if it can be omitted and still have a working circuit.

Thank you for the library.

Chris

**Comment by qhris** [comment]
Hello, respoding a bit late but...

I made this a long time ago and I don't really have any schematics and such anymore, so I can't answer your question sorry.

**Comment by Skylar-8** [comment]
Thank you for responding. 

I understand. I came up with a schematic of my own and I'm hoping it will work well. I'm busy adapting your code to use with ESP32 (Arduino compatible), then I'll test.

Many thanks for your Arduino library. Appreciated!
