### ISSUE TITLE
SPI CS pin hardcoded for all instances?

### ISSUE THREAD

**Issue by felix1024** [qhris/Muses72320#5]
Hi
thanks for this wonderful library!

while testing the library I wonder why the SPI chip select pin definition is hardcoded in the library

static const int s_slave_select_pin = 10;

Wouldn't be far better to set the value in the constructor and store it in the private part of the class?
Furthermore setting the pin to HIGH before defining it as OUTPUT would prevent any glitches.

Kindly
Felix

**Comment by qhris** [comment]
Hey,

You're right, that is a mistake in the initial version of the library, there is also a branch in the repo called `wip-1.0` where you are able to select a different PIN, but it was a long time ago I worked on this, so I'm not sure about the status of that branch. Perhaps you can try it out?

Here is a changelog of the changes between versions: https://github.com/qhris/Muses72320/blob/wip-1.0/CHANGELOG.md

**Comment by felix1024** [comment]
Hey,

Thanks for your kind offer for the branch. I think i’m going to adapt your library to correct that issue. As i’m not a professional C++ programmer, i try to understand your code and adapt it to my requirement. In either case you did a very good job on documentation/interpretation of all bits according to the Muses72320 datasheet! 

May i send you the results of my work on your library for a review?

**Comment by felix1024** [comment]
Voila
https://github.com/felix1024/MCP23S17
Thanks

**Comment by felix1024** [comment]
Hi

i’m sorry just detected, that i published a link to the wrong modified library. 
Correct link is https://github.com/felix1024/Muses72320
